Add title component
ell-ska/jolint pull request #10
Opened 2023-10-18 13:10 UTC by petksks

2023-10-18 16:46 UTC, ell-ska requested changes

2023-10-19 08:29 UTC, ell-ska approved these changes

2023-10-19 08:29 UTC, ell-ska commented on app/consent-form/_components/Title.tsx
> +        <span>{text}</span>
unnecessary span

2023-10-19 08:51 UTC, idamakela commented
It does not crash the site. Good job!

2023-10-19 08:58 UTC, merged