[JOLINT-41] add header
ell-ska/jolint pull request #4
Opened 2023-10-17 12:42 UTC by DavidDyberg

2023-10-17 12:50 UTC, idamakela commented on app/consent-form/_components/Header.tsx
> +    <>
Make Header component to be inside a HTML header tag, because of accessibility?

2023-10-17 12:50 UTC, idamakela commented on app/consent-form/_components/Header.tsx
> +      <hr className='text-neutral-400' />
What is the purpose of the hr tag?

2023-10-17 12:51 UTC, idamakela requested changes
Left two comments inside the code.

2023-10-17 12:53 UTC, idamakela commented on app/consent-form/_components/Header.tsx
> +import React from 'react'
Unused import.

2023-10-17 13:11 UTC, ell-ska requested changes

2023-10-17 13:11 UTC, ell-ska commented on app/consent-form/_components/Header.tsx
>        <div className='m-5'>
change the margin to a padding and put it on the header element

2023-10-17 13:11 UTC, ell-ska commented on app/consent-form/_components/Header.tsx
>          <Image className='bg-white' src={Logo} alt='Logo' />
why is there a bg?

2023-10-17 14:02 UTC, idamakela approved these changes
Looks great and ready for next step!

2023-10-18 09:58 UTC, ell-ska commented
tested on development:
looks great, the only thing is that the border should be neutral-400 instead of 600. change that and it's ready to go!

2023-10-18 10:27 UTC, merged