[JOLINT-62] inclusion section on home page
ell-ska/jolint pull request #46
Opened 2023-10-27 08:16 UTC by petksks

2023-10-27 09:04 UTC, idaakermark requested changes
See comment.

2023-10-30 19:34 UTC, idaakermark approved these changes

2023-10-31 08:46 UTC, petksks commented
Ready for testing. :)

2023-10-31 09:23 UTC, petksks commented
Testing approved.

2023-10-31 09:27 UTC, merged