[JOLINT-42] created footer for consent-form page
ell-ska/jolint pull request #5
Opened 2023-10-17 13:18 UTC by idaakermark

2023-10-17 13:23 UTC, DavidDyberg approved these changes

2023-10-18 09:04 UTC, ell-ska commented
testing on development:
everything looks great but i noticed the social links aren’t links. they probably should be!

2023-10-18 09:05 UTC, ell-ska requested changes

2023-10-18 09:05 UTC, ell-ska commented on app/consent-form/_components/Footer.tsx
> +          <p className='flex gap-4'>
the social links should be <Link>

2023-10-18 09:05 UTC, ell-ska commented on app/consent-form/_components/Footer.tsx
> +          <p className='flex gap-4'>
links

2023-10-19 08:12 UTC, ell-ska commented
testing on development:
good!

2023-10-19 08:16 UTC, ell-ska approved these changes

2023-10-19 08:17 UTC, merged